// @flow
// flow-typed signature: 415af050a598b487411fedc7da90e62f
// flow-typed version: <<STUB>>/is_v3.2.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is' {
  declare module.exports: {
    fn(maybeFn: any): boolean,
    array(maybeArray: any): boolean,
    undefined(maybeUndefined: any): boolean,
    defined(maybeDefined: any): boolean,
    string(maybeString: any): boolean,
    object(maybeObject: any): boolean,
    integer(maybeInteger: any): boolean,
    instance(maybeInstance: any, InstanceOf: any): boolean,
  };
}
