// @flow
// flow-typed signature: 0596a65d628759154765ab18456988d3
// flow-typed version: <<STUB>>/socket.io_v1.7.3/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socket.io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'socket.io' {
  declare module.exports: any;
}
