version: '2.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    expose:
      - "2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    expose:
      - "9092"
      - "29092"
      - "39092"
      - "49092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_HOSTNAME: kafka
      KAFKA_LISTENERS: 'ALWAYSENABLED://kafka:9092, PROXIFIED://kafka:29092, PROXIFIED2://kafka:39092, SMALLTIMEOUT://kafka:49092'
      KAFKA_ADVERTISED_LISTENERS: 'ALWAYSENABLED://kafka:9092,PROXIFIED://kafka:29092, PROXIFIED2://kafka:39092, SMALLTIMEOUT://kafka:49092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'ALWAYSENABLED:PLAINTEXT,PROXIFIED:PLAINTEXT,PROXIFIED2:PLAINTEXT,SMALLTIMEOUT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'ALWAYSENABLED'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 10000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 30000

  toxy:
    image: shopify/toxiproxy
    expose:
      - "9092"
      - "29092"
      - "39092"
      - "49092"
    ports:
      - "8474:8474"
    volumes:
      - '${PWD}/__tests__/docker-configs:/config'
    command:
      - '-host=0.0.0.0'
      - '-config=/config/toxy.json'

  tester:
    image: makeomatic/node:12.15-tester
    hostname: 'tester'
    working_dir: '/src/packages/plugin-kafka'
    volumes:
      - '${PWD}/../../:/src'
    command: 'tail -f /dev/null'
    links:
      - toxy:kafka
    environment:
      NODE_ENV: 'test'
      DEBUG: ${DEBUG}
      UV_THREADPOOL_SIZE: 32
